name: "Lint Code"

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 (non-fatal)
        run: |
          echo "Running flake8…"
          # Lint python under server/ but don't fail the job on findings
          flake8 server --exit-zero --exclude "migrations,frontend,venv,node_modules"
          echo "Linted all the python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run JSHint (non-fatal)
        run: |
          echo "Running JSHint…"
          if [ -d server/database ]; then
            find server/database -type f -name "*.js" -not -path "*/node_modules/*" -print0 \
              | xargs -0 -I {} jshint "{}" || true
          else
            echo "server/database not found; skipping JS lint"
          fi
          echo "Linted all the js files successfully"
